### ISSUE TITLE
codex's sqlite state runtime is not isolated per conversation on a shared sandbox

### ISSUE THREAD

**Issue by jhgaylor** [managoat/fountain#1910]
Split out of #1670, which is closed on its other two halves. This issue tracks the remaining Codex SQLite initialization failure on shared sandboxes.

## Current disposition — 2026-09-22

**Reproduced in production on 2026-09-22 and the mechanism is now evidenced, not inferred: SQLite lock contention (`SQLITE_BUSY`) on a state database shared by many live Codex app-servers.** Two deliverables, in order:

1. **Mitigation (small, Fountain-only, ship first):** retry the peer spawn when `initialize` fails with this specific error, with jittered backoff and a small attempt cap. See "Mitigation" below.
2. **The fix:** per-conversation `CODEX_SQLITE_HOME`, as in "Preferred investigation" below, now for *both* Codex home layouts (see "Two homes since ADR 0060").

The 2026-09-17 assessment (Fountain main `1103fe84`, `managoat_runtimes` 0.4.2, source inspection only) is kept below where it still holds.

## 2026-09-22 production evidence

Read-only: Fountain pod logs, the prod DB, and the sandbox itself (`ls` and a read-only query of Codex's own `logs_2.sqlite`).

- **9 failed turns across 5 conversations, 10:33–10:44 UTC, all on one sandbox** (`7b2d6b59-5a74-400c-941e-6836c77d721c`, sprite `fountain-1633dc35-c82b3439`) and one user ChatGPT grant (`c00d77a5…`, generation `63479ff2…`). Conversations `638dd3a6`, `4c18283b`, `fec50d75`, `b1d684b9`, `68bdb661` (`638dd3a6` once, the other four twice each).
- **Load:** 15 conversations of that grant were started on that sandbox between 09:59 and 10:41 (an app fanning out work on one agent). All share one `CODEX_HOME`, so one `state_5.sqlite`. Codex's log DB in that home records **16 distinct app-server processes**; ~8 were active in the failure windows.
- **Error, verbatim:**
  ```
  {:acp_error, :initialize, %{"code" => 1001, "message" => "Codex process has exited with code 1:\nError: failed to initialize sqlite state runtime under /home/sprite/.codex-grants/<grant>.<generation>: failed to initialize state runtime at /home/sprite/.codex-grants/<grant>.<generation>"}}
  ```
- **The live siblings were hitting the lock in the same hour:** 24 warnings in `logs_2.sqlite`, all in hour 10 UTC, all `error returned from database: (code: 5) database is locked`, from `codex_thread_store::local::update_thread_metadata`, `codex_rollout::list` ("failed to project durable rollout … failed to access thread history") and `live_writer`.
- **Failures pair up:** `638dd3a6`/`4c18283b` were created 3 s apart and their first turns failed within 3 ms of each other on *two different Fountain nodes*; `b1d684b9`/`68bdb661` the same (both at 10:43:08.184). Retries during the burst also failed; later turns succeeded. The ms alignment is unexplained (possibly the sprite exec stream flushing) — do not build on it.
- **Not the symlinks:** the sandbox was fresh at 09:56, so every `*.sqlite` in the grant home is a real file private to that home (listing below), not a link into `~/.codex`. ADR 0060's per-grant home neither caused nor fixed this; with an API key or the platform grant the same 15 conversations would contend in `~/.codex` exactly as on Sep 6.
- **Secondary harm:** after its failed turn, `638dd3a6`'s next turn logged `runtime session is gone (resume_session): no rollout found for thread id …; clearing it and running this turn on a new one` — the conversation silently lost its context (cf. #1670).
- **Versions on that sandbox:** `codex-acp` 1.10.0 running app-server **0.153.4** (`…/@agentclientprotocol/codex-acp/node_modules/@openai/codex/package.json`). The `codex` on `PATH` is **0.151.0** and is *not* what codex-acp runs: record versions from the adapter's `node_modules`, not `codex --version`.

Grant home at 20:47 UTC, abridged: `state_5.sqlite` 300 KB + 4.1 MB WAL, `logs_2.sqlite` 24 MB + 4.1 MB WAL, `thread_history_1.sqlite` 6.6 MB + 2 MB WAL, `goals_1`, `memories_1`, `queue_1`; links `AGENTS.md`, `log`, `sessions`, `skills` → `~/.codex`.

## Mechanism (Codex 0.153.4 source)

- Every app-server opens and migrates each runtime DB at startup and **writes** before it is ready: migrations, then `ensure_backfill_state_row_in_pool` ([runtime.rs#L200](https://github.com/openai/codex/blob/rust-v0.153.4/codex-rs/state/src/runtime.rs#L200)).
- Each connection has `busy_timeout(5s)` ([sqlite.rs#L285](https://github.com/openai/codex/blob/rust-v0.153.4/codex-rs/state/src/sqlite.rs#L285)). With several siblings mid-turn writing thread metadata / history, a starter can wait out 5 s, `StateRuntime::init` fails, and the app-server exits 1 ([app-server lib.rs#L613](https://github.com/openai/codex/blob/rust-v0.153.4/codex-rs/app-server/src/lib.rs#L613)). The corruption-recovery wrapper does not apply to `SQLITE_BUSY`.
- **Diagnosis trap:** that message formats the error with `{err}`, not `{err:#}`, so the cause chain (`database is locked`) is dropped, and a process that fails here never opens its own log DB. The evidence is only in the *siblings'* `logs_2.sqlite` in the same home (`select … from logs where feedback_log_body like '%database is locked%'`). codex-acp keeps only a stderr tail and writes its own `app-server.log` only when `APP_SERVER_LOGS` is set.

## Two homes since ADR 0060

The table below (one root per machine) is no longer the whole picture:

| spawn | `CODEX_HOME` | shared by |
|---|---|---|
| API key / no grant | `/home/sprite/.codex` (library `Layout`) | every such Codex conversation on the machine |
| ChatGPT grant (user subscription or the deployment's grant) | `/home/sprite/.codex-grants/<grant id>.<generation>` | every conversation on that sign-in on the machine |

The grant home is exported as process env by `CodexChatGPT.env/3` and kept out of the shared `.env` by `Identity` (`grant_home?/2`); that is the plumbing a per-conversation `CODEX_SQLITE_HOME` can ride. The home's sharing rules, including why its SQLite files are private or linked depending on order, are in `CodexChatGPT`'s moduledoc and ADR 0060 decision 6 and its "Stage 3 as built" section; #2470 tracks those homes' cleanup. Whatever the fix, it must cover **both** rows, and a grant home must not end up pointing its SQLite at `~/.codex` or vice versa.

## Mitigation: retry initialize on this error

- Scope: the peer spawn's `{:acp_error, :initialize, %{"code" => 1001, "message" => msg}}` where `msg` contains `failed to initialize sqlite state runtime`. Nothing else is retried.
- Jittered backoff (e.g. ~1–3 s, then ~3–8 s), 3 attempts, then fail the turn as today. `initialize` has no side effects to undo.
- Log each retry with the conversation and attempt, so occurrence counts become measurable (they are not today, beyond grepping pod logs).
- Also check the resume path: a turn that retried should not end up in the `no rollout found … clearing it` branch above because of the retry.
- This does not close the issue; it converts most of these into slower turns while the fix is measured.

## The failure and historical evidence (as of 2026-09-17)

`Managoat.Runtimes.Layout` gives every Codex conversation on a machine the same default root:

| runtime | home | config_dir |
|---|---|---|
| codex | `/home/sprite` | `.codex` |

There is no per-conversation SQLite location configured by Fountain. ADR 0023 deliberately allows multiple conversations on one sandbox, so their Codex processes initialize state under the same directory. The reported failure occurs at `initialize`:

```
acp_error, :initialize — Codex process has exited with code 1: Error: failed to
initialize sqlite state runtime under /home/sprite/.codex: failed to initialize
state runtime at /home/sprite/.codex
```

The [September 11 evidence](https://github.com/managoat/fountain/issues/1670#issuecomment-5631742109) recorded five SQLite initialization failures on September 6 and none subsequently in that measured window. Sharing remained heavily exercised: 146 Codex turns on shared sandboxes in the five days after #1662, including 12 distinct Codex conversations on one machine within an hour; the largest sandbox carried 36 live conversations.

#1662 fixed ACP session ownership, not the shared SQLite path. The absence of later failures in that historical window does not establish a fix. No claim is made here about production occurrence counts after September 11. User-visible impact is a failed turn and a conversation that appears dead, as in #1667.

## Dependencies and sequencing

- **No identified hard prerequisite among the current open PRs.** GitHub also records no explicit blocking dependency for this issue.
- **#1662 is merged; #1667 is closed.** Neither needs to land first.
- **Do not wait for #2386 or the rest of #2344 / ADR 0058.** Machine ownership and durable destruction intent address a different problem. Use the existing lifecycle paths rather than introducing another coordinator.
- **Coordinate with #2396 if environment construction is touched.** It changes `SpriteEnv` secret registration and may require a rebase; it is not a functional prerequisite.
- Broader auth isolation from ADR 0053 is related but does not block a SQLite-only reliability fix. Its current admission restrictions must remain in place.

## Preferred investigation: isolate SQLite only

The original proposal assumed moving all of `CODEX_HOME`. OpenAI instead exposes **`CODEX_SQLITE_HOME`** for SQLite-backed runtime state independently of the root holding auth, config, instructions, skills and session files. The `sqlite_home` configuration setting takes precedence over that environment variable. See the [official environment-variable reference](https://learn.chatgpt.com/docs/config-file/environment-variables).

This is supported in the relevant release sources, not only in current documentation:

- Codex [0.153.3 config resolution](https://github.com/openai/codex/blob/rust-v0.153.3/codex-rs/core/src/config/mod.rs#L3953-L3965) and [environment-variable name](https://github.com/openai/codex/blob/rust-v0.153.3/codex-rs/state/src/lib.rs#L108-L109); the same resolution was checked in 0.153.4.
- Fountain pins `codex-acp` 1.10.0. Its [package dependency](https://github.com/agentclientprotocol/codex-acp/blob/v1.10.0/package.json) accepts Codex `^0.153.3`, and its [app-server spawn](https://github.com/agentclientprotocol/codex-acp/blob/v1.10.0/src/CodexJsonRpcConnection.ts#L15-L25) passes the environment through. Record the actual installed Codex version during acceptance; the adapter pin does not freeze that transitive version exactly.

First verify a stable, absolute SQLite directory keyed by **conversation**, retained across turns, wake and restart. It must reach the app-server process before initialization; a session-time configuration change alone is not evidence that the failing startup path is isolated. Existing spawn-environment plumbing may make this a Fountain-only PR without changing the runtime library.

Support in the source does not prove that separate databases solve the reported failure or preserve every resume path. Those are the first acceptance checks.

## Acceptance for a focused fix

- [ ] Reproduce concurrent initialization failing on a shared home (the 2026-09-22 evidence characterizes it: ~8 live writers + new starters on one home) with recorded adapter/Codex versions. Demonstrate distinct SQLite locations and successful concurrent initialization with the fix; distinguish observed failures from the inferred cause.
- [ ] The same conversation retains its location across subsequent turns, peer reuse, fresh process spawn, wake and restart. Different conversations get different locations. Cover bounded and unbounded spawn paths.
- [ ] Existing conversations created with the shared database can resume without losing their runtime session/history. Exercise rollout/reattach compatibility with an already-running adapter; do not move a live database blindly or treat silent session replacement as successful migration.
- [ ] Both home layouts (API key under `~/.codex`, grant under `~/.codex-grants/…`) get per-conversation SQLite; a grant's auth, account and `auth.json` handling are unchanged.
- [ ] API-key and ChatGPT auth, instructions, skills, MCP configuration and broker transport continue working. Preserve the existing inference-source admission guard.
- [ ] Resolve configuration precedence explicitly: `sqlite_home`, environment entries or other overlays cannot silently defeat the promised isolation. Keep the conversation-specific location out of the shared `.env` file.
- [ ] Measure initialization cost and disk growth at the historical 36-conversation scale (one grant home's `logs_2.sqlite` alone reached 24 MB in a day). Define retention and cleanup so active or resumable state is not removed prematurely.

## PR boundaries and `scope:large`

| Chosen approach | Reviewable delivery |
|---|---|
| Mitigation | One small Fountain PR, independent of the rest. |
| SQLite-only isolation passes the checks above | One focused PR is plausible, potentially entirely in Fountain. Include regression and real-runtime evidence with the fix. |
| Full per-conversation `CODEX_HOME` is necessary | First add and release the host-supplied location capability in `managoat_runtimes`; then integrate it in Fountain with the dependency bump, auth/config/instruction/skill preparation, lifecycle paths and existing-session migration. The Fountain consumer change depends on that release. |

Moving the entire home affects more than SQLite: `CodexChatGPT` writes `auth.json` in Fountain, while layout, API-key preparation, instructions and skill mounting span the library and its consumer. Every writer and reader must agree on the new location. Merely exporting `CODEX_HOME` is insufficient.

Keep **`scope:large`** while the reproduction/resume investigation determines which approach is sound; reassess it if the bounded SQLite-only design succeeds. The label denotes investigation or coordinated changes, not a required number of PRs. Priority remains P1; this assessment creates no new ownership or delivery commitment.

## Separate auth-isolation requirement

[ADR 0053 decision 6](https://github.com/managoat/fountain/blob/main/decisions/0053-inference-credential-sets.md#6-a-set-is-not-part-of-sandbox-identity) requires separate per-peer auth locations before different Codex inference sources can share a machine. SQLite-only isolation does **not** satisfy that requirement or justify removing the existing machine source binding. Keep broader auth isolation as separate work unless the full-home approach is deliberately selected and its complete contract is implemented.

**Comment by jhgaylor** [comment]
Deliverable 1 (the mitigation) is merged as #2489 (`1887f7b5`). A Codex adapter that fails `initialize` with `failed to initialize sqlite state runtime` is relaunched up to 3 times, after about 2–4, 6–12 and 15–30 s. The pause is a `sleep` in front of the adapter inside the sandbox. Each relaunch publishes a `session` stage event with `reason: "runtime_state_locked"` and logs `codex could not open its sqlite state; launching it again`. Those lines, next to any remaining `acp peer failed … sqlite state runtime` errors, are this issue's occurrence count from now on. It only fits unbounded turns; the per-conversation `CODEX_SQLITE_HOME` fix (deliverable 2) is still the work here.
