### ISSUE TITLE
Tracking: post-launch gap audit (2026-07-31)

### ISSUE THREAD

**Issue by jhgaylor** [managoat/fountain#200]
Index for the post-launch gap audit run on 2026-07-31, covering product surface, self-hosting readiness, billing/cloud, security/tenancy, and operations. All child issues carry the `audit-2026-07` label.

**Scope note:** this repo is public, so the security issues below are written in remediation terms — impact, location and fix direction, without reproduction steps. Happy to move any of them to a private advisory if you'd rather they weren't visible while unfixed.

## Headline

The engineering craft here is good — clean tenant-scoping convention, real envelope encryption, Horde clustering with crash rehydration, ADRs for every significant decision, SHA-pinned CI with gitleaks and sobelow. The gaps are not sloppiness; they are **missing wiring around code that already exists**.

Two of those gaps are load-bearing for the business model:

1. **Cloud revenue is structurally near-zero.** Trials never expire (#153), the billing gate is bypassable with one API call (#154), paying customers can be charged and never activated (#156), and usage metering has no call sites (#159).
2. **Self-hosting is a stated goal, not a supported path.** There is no LICENSE (#183), no self-host guide or working compose file (#184), Postgres TLS is hardcoded on (#185), and the sandbox backend can't be repointed (#189).

Alongside those, **cost exposure is unbounded** — Fountain pays the Sprites bill per ADR 0005, with no quota (#160), no metering (#159), no idle timeout (#167), no reaper (#166) and open registration (#188).

## The systemic finding

Three mechanisms are asserted as implemented in ADRs and module docstrings, and do not exist in code:

| Claimed | Claimed where | Reality |
|---|---|---|
| `Fountain.Quotas.check_sandbox_quota!/1` | `decisions/0005:22` | No such module. `max_concurrent_sandboxes` is cast but never read. (#160) |
| `Billing.emit/5` called at provision / turn / terminate | `billing.ex:175` docstring | Zero call sites. `usage_events` is permanently empty. (#159) |
| Subscription gate in `ConversationServer.init/1` | `billing.ex:11`, `decisions/0006:31` | Not there. Only two gate sites exist. (#155) |

Anyone auditing this system by reading the ADRs concludes it is metered, quota-capped and gated. It is none of those. Worth treating "ADR claims are unverified" as a standing assumption until each is re-checked — and worth a convention that an ADR describing unbuilt behaviour says so explicitly.

## P0 — cost, data loss, revenue, security

**Revenue**
- [ ] #153 — trials never expire; no Stripe subscription created at trial start
- [ ] #154 — `POST /api/conversations/:id/prompts` is not subscription-gated
- [ ] #155 — add the `ConversationServer` backstop ADR 0006 already claims exists
- [ ] #156 — Checkout without an existing customer orphans the subscription
- [ ] #157 — OAuth signups never get a Stripe customer or `trial_ends_at`
- [ ] #159 — usage metering is a no-op

**Cost**
- [ ] #160 — `Fountain.Quotas` does not exist; concurrency cap unenforced

**Data loss / operability**
- [ ] #161 — no Postgres backups configured on the live cluster
- [ ] #162 — no error tracking, tracing disabled, request logging off

**Security**
- [ ] #171 — API keys have no scopes or expiry; sprite callback tokens are full-privilege
- [ ] #172 — master secrets key falls back to a repo-known constant when `PHX_SERVER` is unset
- [ ] #173 — turn image endpoint is missing tenant scoping

**Licensing**
- [ ] #183 — no LICENSE file, while the Homebrew formula claims MIT

## P1 — fix soon

**Billing** · #158 webhook idempotency
**Ops** · #163 health endpoint · #164 unbounded log retention · #165 no durable job queue · #166 no orphan reaper · #167 no sandbox idle timeout · #170 no account deletion
**Security** · #174 unvalidated `parent_conversation_id` · #175 rate limiting keys on proxy IP · #176 browser login unlimited · #177 audit covers API only · #178 provisioning hardening · #179 secrets can land in `log_events`
**Self-host** · #184 compose + guide · #185 Postgres TLS · #186 `FOUNTAIN_DOMAIN` split · #187 silent mail fallback · #188 `BILLING_ENABLED` + registration allowlist
**Testing** · #192 `ConversationServer` untested · #193 SSE untested · #194 Go tests never run
**Docs / CLI** · #195 `docs/cli.md` is fictional · #196 CLI exits silently mid-turn

## P2 — worth doing

#168 retries/circuit breakers · #169 admin tooling · #180 transport hardening · #181 OAuth email linking · #182 tenancy naming hygiene · #189 `SPRITES_BASE_URL` · #190 version-tagged images · #191 portable k8s baseline · #197 unreachable `completed` status · #198 `/api/agents` ignores filters · #199 `/llms.txt` broken help link

## Suggested order

1. **Stop the bleeding** — #161 (backups; one bad migration from unrecoverable loss), #160 + #167 + #166 (bound the Sprites bill), #162 (so you can see any of it happening).
2. **Turn on revenue** — #153, then #155 (which closes #154 and future leaks in one place), then #156 + #157, then #159.
3. **Close the security gaps** — #171 and #172 first, then #173 and #175.
4. **Make self-hosting real** — #183 first; nothing else on that track matters until the license exists.

Existing related work: #148 (token-only sandboxes) is the design-level answer to #179, and #171 complements it — #148 removes secret *values* from the sprite, #171 constrains the token the sprite legitimately holds.

**Comment by jhgaylor** [comment]
## Progress — first pass on the P0s

Two PRs open, both green on CI, independent of each other and safe to merge in either order.

**#202 — security P0s.** Closes #173 (turn images were readable across tenants from both the API and the browser route) and #172 (master secrets key fell back to a repo-known constant whenever `PHX_SERVER` was unset). Verified the new isolation tests fail against the unpatched code rather than passing vacuously.

**#204 — the production link defect.** Closes #186. `FOUNTAIN_DOMAIN` fed both an absolute base URL and a bare host, so `:public_url` was schemeless. Merging fixes production with **no deploy-time env change** — confirmed by evaluating `runtime.exs` through `Config.Reader` with production's current variables.

### Two things found while fixing, worse than what was originally filed

**The schemeless URL is not just an email bug.** The same value is handed to every sprite as `FOUNTAIN_BASE_URL` (`conversation_server.ex:857`), so in-sprite agent callbacks are affected too. Broader blast radius than #186 described — worth checking a real conversation once #204 lands.

**A stored-XSS vector, now filed as #203.** `TurnImage.changeset/2` — including its media-type allowlist — is never called anywhere. Every row arrives via `insert_turn_images/2`, which uses `Repo.insert_all` against a raw table name and skips the changeset entirely, and `decode_images/1` takes `media_type` straight from client JSON. A client could store `text/html` and have it served back as `Content-Type: text/html` from the app's own origin. Combined with #173, that content was reachable by *other* tenants. #202 closes it at the serve boundary (which also neutralises any rows already stored); ingest-side validation is #203.

Also noted on #194: the CI `sobelow` step runs from the umbrella root, where sobelow scans nothing and exits 0. That security gate has never inspected this codebase.

### Not started
- **#161 (backups)** is the remaining "stop the bleeding" item and needs a decision I can't make: which object store the CNPG backups go to, and where those credentials live.
- **#160 (quotas)** is the next fully codeable one.

**Comment by jhgaylor** [comment]
## Progress update

**Merged:** #202 (security P0s — #172, #173) and #204 (production link defect — #186). Both verified together on `main` afterwards, since they were developed independently and both touch `runtime.exs`: 1102 tests green, and the prod config path re-checked with production's real variables.

**Open and green:** #205 closes #160 — the concurrent-sandbox cap that ADR 0005 specified and was never built. Enforced on both provisioning paths, including the wake path, which otherwise lets the cap be bypassed by prompting instead of creating (same shape as the #154 billing leak).

Along the way it turned out the cap was documented as admin-adjustable but **nothing could adjust it** — no changeset covered the column on an existing user, so both documented remedies (raise for a trusted tenant, drop to zero during abuse) needed `psql`. #205 adds the changeset, context function, and an admin control showing live usage against the cap. Shipping enforcement without that lever would have made the first legitimate power user an incident.

### This changes the priority of two other issues
#166 (orphan reaper) and #167 (idle timeout) were filed as cost hygiene. With a cap enforced, a leaked sandbox permanently consumes tenant quota, so those become **user-visible lockouts with manual-only recovery**. Noted on #166; both worth pulling forward.

### Remaining P0s
- **#161 (backups)** — still the top unaddressed risk, and still blocked on a decision I can't make: which object store CNPG backups go to and where those credentials live.
- **#162 (observability)** — no error tracking, tracing off, request logging off.
- **#171 (API key scoping)** — sprite callback tokens are full-privilege tenant keys.
- The revenue cluster (#153, #155, #156, #157, #159) is untouched.

**Comment by jhgaylor** [comment]
## Progress update

**Merged:** #202 (#172, #173), #204 (#186), #205 (#160).

**Open and green:** #206 closes #171 — the sandbox privilege escalation.

Every conversation hands its sprite an unrestricted tenant key, and `POST /api/auth/api-keys` is in the same bearer pipeline, so code in a sandbox could mint a second key that the conversation-scoped revoke at teardown knows nothing about. #206 adds scopes (existing keys backfill to `full`, so nothing changes on deploy) and gates key management at the router.

The cut is deliberately narrow: sprite tokens keep the full resource surface, because spawning sub-agents from inside a sprite is a supported workflow — only key *minting* is denied, since that is what converts a scoped credential into an unscoped one. Confirmed the escalation tests fail against the unguarded router.

It also adds `expires_at` on callback tokens, which partly addresses the API-key half of #166: an orphaned token is now bounded rather than valid forever. **The sprite half of #166 is untouched** and, per the note there, now matters more because leaked sandboxes consume quota.

### Remaining P0s
- **#161 (backups)** — still the top unaddressed risk, still blocked on your call about object store + credentials.
- **#162 (observability)** — no error tracking, tracing off, request logging off.
- Revenue cluster (#153, #155, #156, #157, #159) — untouched. Worth noting these are the reason the cloud variant currently collects nothing.

### Worth a decision
`sprite` scope is currently "everything except key management". A sprite token can still delete environments and vaults. Narrowing further is a product question — what should sub-agent workflows be able to do? — rather than a security judgement I should make unilaterally.

**Comment by jhgaylor** [comment]
## Progress update — backups

**Merged:** #202, #204, #205, #206, #207, #208. That closes #172, #173, #186, #160, #171 and **#161**.

### #161 was not the fix the issue described

The issue assumed CNPG's `spec.backup.barmanObjectStore`. **That would have silently archived nothing.** CNPG here is 1.29.1, and as of 1.26 barman-cloud moved out of the operand images into a separate plugin — the running image has no `barman-cloud-*` binaries and no Python, and neither the plugin nor its `ObjectStore` CRD is installed. Writing the "obvious" manifest would have closed #161 with the problem fully intact and a Cluster reporting healthy.

Shipped instead: a nightly `pg_dump` to a private Garage bucket, self-contained in this repo. **Verified by actually restoring it** — a real artifact pulled from the bucket into a scratch database matched live on every table (users 191, agents 45, conversations 255, environments 22, vaults 5). Two problems surfaced only by running it: Garage answers `HeadObject` with `400`, so `aws s3 cp` cannot download and my first size-check failed 100% of the time; and default progress output is hundreds of KB of log per run.

The temporary `CREATEDB` grant needed for the restore test was revoked and confirmed (`rolcreatedb = f`), scratch DB dropped, test artifacts pruned.

Limits, recorded honestly: 24-hour recovery granularity, no PITR (#209), Garage shares a cluster with the database it backs up, and **nothing alerts if the job stops running** — blocked on #162.

### Incidental findings from the restore
- **`api_keys` has 24,115 rows** for 255 conversations. Sprite tokens rotate on every provision and reattach and are only revoked on clean teardown. #206 bounds new ones with an expiry; the backlog needs #166's reaper.
- **`log_events` has 97,015 rows** — #164, on a 10Gi volume.

### Remaining P0s
- **#162 (observability)** is now the top item and is fully actionable: no error tracking, tracing off in prod, request logging off. It also gates alerting for the backup job and for #164's disk growth.
- The revenue cluster (#153, #155, #156, #157, #159) is untouched — still the reason the cloud variant collects nothing.

**Comment by jhgaylor** [comment]
## Progress update — observability

**#210 merged and verified running in production.** Closes #162.

The cluster already had kube-prometheus-stack, Alertmanager→ntfy, Loki+Alloy and Grafana — none of it pointed at Fountain. So this was wiring, not procurement: no SaaS, no account, no new infrastructure.

Verified live after the rollout, not just in CI:

- both pods scraped, `up=1`, **39 real requests already counted** in Prometheus
- all **9 alert rules loaded and inactive**
- `/metrics` and `/health` serving on `:9568`, everything else 404
- request logs flowing again (`GET /health ... Sent 200 in 306µs`) — production previously kept no record of HTTP requests at all

### Two traps avoided by checking rather than assuming
- The existing `metrics/0` is entirely `summary/2`, which the Prometheus reporter **does not implement** — reusing it raises at boot, in production, after a deploy. Prometheus gets its own list, and a test pins that no `summary` creeps back in.
- **Every alert expression was run through the live Prometheus API.** A rule with a syntax error simply never loads — the same silent-failure class as the barman-cloud trap in #208. Label names were read off a real ServiceMonitor target rather than guessed.

Metrics are on a separate port deliberately: the IngressRoute matches on `Host` with no path predicate, so anything on the Phoenix endpoint is world-readable, and the scrape payload enumerates routes, request rates and DB timings.

### The backup loop is now closed
`FountainBackupStale` / `NeverSucceeded` / `JobFailing` / `Suspended` mean the CronJob from #208 can no longer rot silently — which was the open caveat on that PR.

### Not done, deliberately
- **Traces stay off.** No Tempo/Jaeger/collector exists in the cluster (checked); enabling the exporter without one floods logs with `localhost:4318` retries.
- **Error tracking** — split to #211. Sentry vs self-hosted GlitchTip is a hosting decision for you; the app-side diff is identical either way.

### Where the P0s stand
All infrastructure P0s are now closed: #161 (backups), #162 (observability), #160 (quotas), #171/#172/#173 (security), #186 (prod link defect), #183 remains open (LICENSE).

**The revenue cluster is the last untouched P0 group** — #153, #155, #156, #157, #159. Trials never expire, the gate is bypassable via the prompt endpoint, OAuth signups can pay and never activate, and metering has no call sites. That is still why the cloud variant collects nothing.

**Comment by jhgaylor** [comment]
## Progress update — revenue cluster

**Merged:** #212 (#154, #155, #156, #157), #213 (#159), #214 (#158).

Everything actionable in the revenue cluster is now closed. **#153 is the only one left and it is blocked on a product decision, not on engineering.**

### What shipped
- **The gate now sits where sprites are provisioned**, so prompting a dormant conversation — which provisions a fresh sprite and had no billing check at all — can no longer be used to spend indefinitely after cancelling. Same choke point as the quota check.
- **Checkout can no longer orphan a payment.** It creates the Stripe Customer first and never falls back to `customer_email`, carries `client_reference_id`, and `checkout.session.completed` backfills the link — which repairs the 153 existing accounts that had no customer id, lazily, as they transact.
- **Usage is actually metered.** `Billing.emit/5` had a schema, a migration, docs and unit tests and zero call sites, so `/account/billing` showed zeros to everyone. It now emits from `update_sandbox/2` and `create_turn/1`, counting transitions only.
- **Webhooks are idempotent and order-aware**, so a replay can't resurrect a cancelled account and a stale event can't lock out a paying one. The controller also stopped answering 200 to failures, which had been discarding Stripe's retry mechanism entirely.

### Pattern worth noting
Three of these bugs shared a shape: a mechanism that was documented, schema'd and unit-tested, but never wired to the operation it was supposed to measure or guard. In each case the existing tests passed throughout. The new tests assert from the operation rather than the helper, and I verified each by reverting the fix — 5, 9 and 5 failures respectively.

Two bugs were found *by writing the tests*: `prompt/2` had no clause for the new error tuple and would have returned 500 instead of 402, and the same defect had existed for the quota tuple. That `case` has now had three error shapes threaded through it by hand; a fourth will likely break the same way.

### Blocked on you
**#153 — trials never expire.** Until this lands the practical revenue effect of everything above is still zero. It needs the pricing decision first:

1. **What is the product?** The marketing page advertises "$29/mo per team" in two places and there is no team or org entity in the schema.
2. **Stripe-driven or local trial expiry?** A real subscription with `trial_period_days` (Stripe drives the lifecycle, handles dunning) versus `assert_active!` comparing `trial_ends_at` to the clock (simpler, no scheduler needed).
3. **Does the hard gate survive at all**, or become cloud-only config? It currently blocks self-hosters too (#188).

**Comment by jhgaylor** [comment]
## Progress update

**Merged since the last update:** #215 (#174), #216 (#175, #176), #217 (#165, #164).

### Corrections to earlier claims in this thread
Two things I asserted turned out to be wrong once I looked at production rather than the code:

- **The API key accumulation is not a leak.** 24,135 rows but only 11 live — revocation works correctly. It was a retention problem, now fixed by #217.
- **There is no meaningful sandbox leak.** 5 `ready`, 4 stale. #166's reaper is far less urgent than I implied when the quota work landed. Also: 183 of the 188 failed sandboxes were launch week; recent weeks run 4 failed against 25 terminated.

### #174 — cross-tenant conversation graph
Closed. Also ran the production check: **zero cross-tenant parent links**, so the hole was real but never exercised. 134 of 255 conversations use the spawn graph, all within one tenant. Found a latent DoS while rewriting — the recursion had no depth bound and parent links are client-supplied, so a cycle would have spun the CTE indefinitely.

### #175 / #176 — client IP and login limits
Production confirmed the diagnosis exactly: every recent `audit_events.request_ip` was `10.42.0.0` or `10.42.0.1`, the cluster gateway. So per-IP limits were global.

**My first implementation had a security hole and a test caught it.** `RemoteIp` returns the rightmost non-proxy address *without checking whether the peer is a proxy*, so a direct client could forge `X-Forwarded-For` and be believed — making rate limiting opt-out. The header is now only consulted for connections from a trusted proxy.

**Open question for you:** whether this recovers true client addresses depends on the deployment, not the code — Traefik runs `hostNetwork` behind Lima port-forwarding, so the address may be lost upstream. The resolved IP is now logged per request, so after a deploy this is one query:
```
{namespace="fountain"} | remote_ip != "" | remote_ip !~ "10.4[23].*"
```
Empty result means it needs a Traefik/Lima change too.

### #165 / #164 — job queue and retention
`log_events` is 114MB of a 155MB database. The 90-day default **deletes nothing today** (no row is older than 90 days) — it bounds growth from here and leaves room to choose a different number first. Pruning runs at 04:23, after the 03:17 backup, so a backup always captures the pre-prune state.

Stripe customer creation is now a durable job rather than a `Task.async` linked to the request process — the mechanism behind 153 accounts having no customer id.

### Still blocked on you
- **#153** — trials never expire. The pricing question.
- **#183** — licensing. Parked; your stated intent ("anyone can self-host, only I can sell it") points at a source-available non-compete licence rather than MIT/Apache/AGPL, whenever you want to pick one.

**Comment by jhgaylor** [comment]
## Progress update — self-hosting

**Merged:** #224 (#185, #188) and #225 (#184).

Self-hosting now has an actual path: `cp .env.compose.example .env`, fill two generated keys, `docker compose up -d`. Previously `docker-compose.yml` started only Postgres, and Postgres TLS was hardcoded on — so the canonical containerised setup could not connect to its own database.

Also added: `BILLING_ENABLED` (ADR 0006 called the gate a product invariant, which is a lock with no key on a self-hosted instance), `REGISTRATION_ENABLED` / `REGISTRATION_ALLOWED_EMAIL_DOMAINS`, and `DATABASE_SSL_VERIFY` so the app can authenticate its database rather than merely encrypt to it.

Both gates went in the **context**, not the controllers: there are three ways to create an account — HTML form, JSON endpoint, and an OAuth callback for an unrecognised identity — and the OAuth path is exactly the one a controller-level check would miss.

### Verification limit worth recording
**There is no container runtime on this machine, so I have not run `docker compose up`.** What I did verify: the YAML parses, `depends_on` gates on health, every referenced variable is documented (a programmatic check caught two I had missed), and the application config resolves correctly under exactly the environment the compose file sets. That last one matters most, because every historical failure here was config resolution rather than compose syntax — TLS hardcoded, `PUBLIC_URL` schemeless, mail silently discarded. A real `docker compose up` is still the outstanding test.

### The remaining self-host blocker is yours
**#183 — there is still no LICENSE**, so strictly nobody has permission to run any of this. The guide says so in its "known gaps" section rather than pretending otherwise. Your stated intent — anyone can self-host, only you can sell it — points at a source-available non-compete licence (FSL, Elastic v2, BSL, PolyForm Shield) rather than MIT/Apache/AGPL, whenever you want to pick one.

### Where the audit stands
Every P0 is closed except #183. Remaining P1s: #163 (health endpoint checks nothing), #166/#167 (reaper, idle timeout — both lower priority than first thought, since production shows almost no leakage), #170 (account deletion), #178 (provisioning hardening), #193 (SSE untested), #194 (CI gates), #203 (turn image ingest), #209 (PITR), #211 (error tracking — needs your Sentry vs GlitchTip call), and #153 (trial expiry — needs the pricing call).

**Comment by jhgaylor** [comment]
## Progress, 2026-08-01

**Every P0 and P1 in this audit is now closed except the two that need a decision from you** (#153 and #211, both below).

Closed since the last update: #163 health probes, #166 sandbox reaper, #167 sandbox lifetime, #170 account deletion, #180 transport hardening, #181 OAuth verified email, #189 SPRITES_BASE_URL, #193 SSE tests, #194 CI gates, #198 agent filters, #199 help topics, #201 SSE 406, #203 turn image ingest.

Three new issues came out of the work rather than the audit: #228 (SSH clone documented but rejected), #231 (Flux deploy ordering — which then fired for real during a rollout), #236 (dialyzer cannot gate yet).

### Blocked on a decision

- **#153** — trial expiry. Needs the pricing model settled: marketing says "$29/mo per team" and there is no team entity in the schema.
- **#211** — error tracking. Sentry vs self-hosted GlitchTip.
- **#228** — enable SSH repository clones or delete the code and the docs section.
- **#148** — token-only sandboxes is an architecture decision, not a fix.

### Ready to do, not started

#168 (retries/backoff), #169 (admin billing-blind), #182 (`_unsafe_` naming), #190 (version tags), #191 (portable k8s chart), #197 (`completed` status / `exit_code`), #209 (PITR — needs object storage decisions), #231, #236.

**Comment by jhgaylor** [comment]
Closing the audit tracker: **every child issue is closed** except #209, whose implementation is merged-pending as #270 (the cluster-wide prerequisite is already live via home-cloud#36) — it closes on that PR's merge tonight.

Scoreboard against the audit's own headlines:
- **"Cloud revenue is structurally near-zero"** — trials are real Stripe subscriptions that expire and warn (#244/#251), the gate is enforced on every provisioning path (#212), checkouts can't orphan (#212), metering emits (#213), and the legacy free-forever cohort was investigated (it was 1 test account + 158 bot signups) and expired.
- **"Self-hosting is a stated goal, not a supported path"** — MIT license (#226), compose + guide (#225), DB TLS/billing/registration switches (#224), `SPRITES_BASE_URL` (#189), version-tagged images (#190), portable k8s baseline (#191).
- **"Cost exposure is unbounded"** — quotas enforced (#205), idle/lifetime bounds (#233), reaper (#232), metering (#213), and registration abuse now has a decided countermeasure (#259).
- **The systemic finding** (ADRs claiming unbuilt mechanisms) — all three phantom mechanisms are now real, and the preventive convention is #271.

Residue: #209→#270 (tonight), #148 (ADR #267 awaiting accept/amend), #259 (Cloudflare rule to click), #271 (convention + sweep). All individually tracked; the tracker has nothing left to track.
